/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TourPlanRouteImport } from './routes/tour-plan'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PersonNameRouteImport } from './routes/person.$name'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'

const TourPlanRoute = TourPlanRouteImport.update({
  id: '/tour-plan',
  path: '/tour-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonNameRoute = PersonNameRouteImport.update({
  id: '/person/$name',
  path: '/person/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/tour-plan': typeof TourPlanRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/users': typeof AdminUsersRoute
  '/person/$name': typeof PersonNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/tour-plan': typeof TourPlanRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/users': typeof AdminUsersRoute
  '/person/$name': typeof PersonNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/tour-plan': typeof TourPlanRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/users': typeof AdminUsersRoute
  '/person/$name': typeof PersonNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reports'
    | '/tour-plan'
    | '/admin/activity'
    | '/admin/approvals'
    | '/admin/users'
    | '/person/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reports'
    | '/tour-plan'
    | '/admin/activity'
    | '/admin/approvals'
    | '/admin/users'
    | '/person/$name'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/reports'
    | '/tour-plan'
    | '/admin/activity'
    | '/admin/approvals'
    | '/admin/users'
    | '/person/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  TourPlanRoute: typeof TourPlanRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  PersonNameRoute: typeof PersonNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tour-plan': {
      id: '/tour-plan'
      path: '/tour-plan'
      fullPath: '/tour-plan'
      preLoaderRoute: typeof TourPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$name': {
      id: '/person/$name'
      path: '/person/$name'
      fullPath: '/person/$name'
      preLoaderRoute: typeof PersonNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  TourPlanRoute: TourPlanRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminUsersRoute: AdminUsersRoute,
  PersonNameRoute: PersonNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
